### ISSUE TITLE
update readme/wiki entry for installation

### ISSUE THREAD

**Issue by nevion** [spyder-ide/spyder.vim#6]
currently a bit too sparse on details to understand how to use, for me a,  spyder plugin newbie

**Comment by Nodd** [comment]
Yeah, plugins are for the next spyder version (3.0), so if you don't use development version you can't use plugins. I'll update the readme when plugins are more stable.
For reference the documentation for plugins is in the [github wiki](https://github.com/spyder-ide/spyder/wiki/User-plugins).

**Comment by nevion** [comment]
FYI I am using spyder 3.. and qt5 :-)

**Comment by Nodd** [comment]
Oh, great !
The easiest way to test it right now is to use the command `pip install git+git://github.com/spyder-ide/spyder.vim.git`. I can't test it because of proxy issues, does it work for you ?

**Comment by nevion** [comment]
mostly works with beta4 - but the cursor is not being displayed/moving while in command mode - however something is being manipulated because I see opening/closing parenthesis highlighted as I move the cursor about with vimkeys.

Btw - I spent alot of time with .spyder-py3/userplugins to no avail, pip installing was the way to go with anaconda (windows).

**Comment by Nodd** [comment]
Sorry, `userplugins` was a documentation mistake, the actual directory is `spyplugins` (I updated the doc). The README is updated too.

Yeah, the development of this plugin is still in the early stage. See #2 for the cursor issue for example.
