### ISSUE TITLE
Make this plugin based on FakeVim

### ISSUE THREAD

**Issue by Zaharid** [spyder-ide/spyder.vim#9]
Copied from https://github.com/spyder-ide/spyder/issues/3304#event-728095831, as requested:

I was wondering if it would be feasible to use FakeVim:

https://github.com/hluk/FakeVim

This works very well in QtCreator, and does neat things like reading the default .vimrc file, allowing search or block text selection.

**Comment by Nodd** [comment]
Thanks, that's interesting, I'll have a look at it. The features are interesting, but there is not a lot of documentation, and I'm not sure if it can work as an external plugin (vs being embedded in the editor itself).

**Comment by Nodd** [comment]
So, after more research, here is what I found about FakeVim
* It's C++, so it needs to be compiled
* It's not present on pypi
* It works with PyQt only (not necessarily a big problem since PySide is not officially supported in spyder)
* It needs to be compiled with the correct PyQt version, so no Qt4/Qt5 compatibility

For these reasons I won't use it for this plugin, even if there are lots of features absent from spyder.vim that I will have to recode.

**Comment by nevion** [comment]
hmm.. I'm a long time user of fakevim on qtcreator.  I reported several bugs and watched how long it took (~2 years to get good, still has issues tho).  If you're doing it in pure python, things may take less long but it still is going to be a long effort - I think, doing it in house.  I will note that their implementation is not full vim either - I hit edge cases often there too, but you get used to them and it's worth the sacrifice.

On your list, the only thing we can really address is pypi.

Maybe as an alternate you could translate the C++ stuff over to python... though I'd still want to keep that a fakevim project so it can be reused.  Needing a vim widget does come up pretty often in peoples wishlist.  I also find C++ Qt ports pretty easily to do to python Qt.

**Comment by Nodd** [comment]
I agree that it will be a big effort (I'm counting on user contributions too!), but if only 1/10th of users are able to actually install the plugin it's not worth it (compiling python extensions on windows is really hard).

FakeVim licence is LGPL, I'm not sure if it's possible to simply translate the lib (I thought about it too).
